spring:
  application:
    name: employee-api-r2d

server:
  port: 7878

logging:
  level:
    org.springframework: info

datasource:
  host: localhost
  port: 5432
  database: testdb
  username: postgres
  password: admin
